/**
 * Financial Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BankAccountsPost { 
    bankId: string;
    /**
     * ISO 4217 currency code
     */
    currency: string;
}

