/**
 * Financial Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsurancePolicyActionPost { 
    /**
     * Action to perform on the insurance policy
     */
    action: InsurancePolicyActionPost.ActionEnum;
}
export namespace InsurancePolicyActionPost {
    export type ActionEnum = 'suspend' | 'reactivate';
    export const ActionEnum = {
        Suspend: 'suspend' as ActionEnum,
        Reactivate: 'reactivate' as ActionEnum
    };
}


