/**
 * Financial Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsurancePolicyGet { 
    /**
     * Id of the created resource
     */
    readonly id: string;
    startDate: string;
    endDate: string;
    insurancePolicyProductId: string;
    bankAccountId: string;
    /**
     * Current status of the insurance policy
     */
    readonly status?: InsurancePolicyGet.StatusEnum;
}
export namespace InsurancePolicyGet {
    export type StatusEnum = 'ACTIVE' | 'SUSPENDED' | 'TERMINATED';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Suspended: 'SUSPENDED' as StatusEnum,
        Terminated: 'TERMINATED' as StatusEnum
    };
}


