/**
 * UniPegaso Banking API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsurancePoliciesPost { 
    startDate: string;
    endDate: string;
    insurancePolicyProductId: string;
    bankAccountId: string;
}

