/**
 * Financial Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvestmentGet { 
    /**
     * Id of the created resource
     */
    readonly id: string;
    amount: number;
    readonly startDate?: string;
    endDate: string;
    investmentProductId: string;
    bankAccountId: string;
    /**
     * Current status of the investment
     */
    readonly status?: InvestmentGet.StatusEnum;
}
export namespace InvestmentGet {
    export type StatusEnum = 'ACTIVE' | 'CLOSED';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Closed: 'CLOSED' as StatusEnum
    };
}


