/**
 * UniPegaso Banking API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvestmentActionPost { 
    /**
     * Action to perform on the investment
     */
    action: InvestmentActionPost.ActionEnum;
}
export namespace InvestmentActionPost {
    export type ActionEnum = 'activate' | 'close';
    export const ActionEnum = {
        Activate: 'activate' as ActionEnum,
        Close: 'close' as ActionEnum
    };
}


