/**
 * UniPegaso Banking API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanGet { 
    /**
     * Id of the created resource
     */
    readonly id: string;
    amount: number;
    readonly startDate?: string;
    endDate: string;
    loanProductId: string;
    bankAccountId: string;
    /**
     * Current status of the loan
     */
    readonly status?: LoanGet.StatusEnum;
}
export namespace LoanGet {
    export type StatusEnum = 'ACTIVE' | 'CLOSED';
    export const StatusEnum = {
        Active: 'ACTIVE' as StatusEnum,
        Closed: 'CLOSED' as StatusEnum
    };
}


