/**
 * Financial Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanProductsPost { 
    name: string;
    rate: number;
    /**
     * Type of the loan
     */
    type: LoanProductsPost.TypeEnum;
}
export namespace LoanProductsPost {
    export type TypeEnum = 'PersonalLoan' | 'HomeMortgage' | 'CreditCard';
    export const TypeEnum = {
        PersonalLoan: 'PersonalLoan' as TypeEnum,
        HomeMortgage: 'HomeMortgage' as TypeEnum,
        CreditCard: 'CreditCard' as TypeEnum
    };
}


