/**
 * UniPegaso Banking API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileGet { 
    /**
     * Id of the created resource
     */
    readonly id: string;
    name: string;
    surname: string;
    email: string;
    password: string;
    taxIdentificationNumber: string;
    birthDate?: string;
    birthCountry?: string;
    birthState?: string;
    birthCity?: string;
    readonly createdAt?: string;
    readonly lastLogin?: string;
}

