/**
 * Financial Management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfilesGetInner { 
    /**
     * Id of the created resource
     */
    readonly id: string;
    readonly createdAt?: string;
    readonly lastLogin?: string;
    email?: string;
}

