export * from './auth.service';
import { AuthApiService } from './auth.service';
export * from './bank.service';
import { BankApiService } from './bank.service';
export * from './bankAccount.service';
import { BankAccountApiService } from './bankAccount.service';
export * from './insurancePolicy.service';
import { InsurancePolicyApiService } from './insurancePolicy.service';
export * from './insurancePolicyProduct.service';
import { InsurancePolicyProductApiService } from './insurancePolicyProduct.service';
export * from './investment.service';
import { InvestmentApiService } from './investment.service';
export * from './investmentProduct.service';
import { InvestmentProductApiService } from './investmentProduct.service';
export * from './loan.service';
import { LoanApiService } from './loan.service';
export * from './loanProduct.service';
import { LoanProductApiService } from './loanProduct.service';
export * from './transaction.service';
import { TransactionApiService } from './transaction.service';
export * from './userBankAccount.service';
import { UserBankAccountApiService } from './userBankAccount.service';
export * from './userProfile.service';
import { UserProfileApiService } from './userProfile.service';
export const APIS = [AuthApiService, BankApiService, BankAccountApiService, InsurancePolicyApiService, InsurancePolicyProductApiService, InvestmentApiService, InvestmentProductApiService, LoanApiService, LoanProductApiService, TransactionApiService, UserBankAccountApiService, UserProfileApiService];
